# Generated by Django 3.1.3 on 2021-04-13 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posted_On', models.DateField(auto_now_add=True)),
                ('Review', models.TextField()),
                ('Rating', models.PositiveIntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentenrolledtutor', to='accounts.student')),
                ('Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorreviews', to='accounts.teacher')),
            ],
            options={
                'ordering': ['-Posted_On'],
            },
        ),
        migrations.CreateModel(
            name='MakeAppointment',
            fields=[
                ('dateTime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('timezone', models.CharField(default='', max_length=35)),
                ('recc', models.BooleanField(help_text='Reccurance')),
                ('pattern', models.CharField(default='', help_text='D-Daily/W=Weekly', max_length=2, null=True)),
                ('repeat', models.DecimalField(decimal_places=0, default=-1, max_digits=3, null=True)),
                ('days', models.CharField(default='', max_length=50, null=True)),
                ('endingDate', models.DateField(null=True)),
                ('daysDump', models.TextField()),
                ('utcDateTime', models.DateTimeField()),
                ('utcEndingDate', models.DateField(null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(default='', max_length=50)),
                ('created_by', models.BooleanField(blank=True, default=False, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MakeAppointment', to='accounts.student')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MakeAppointment', to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='enrollTutors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=100)),
                ('forclass', models.CharField(default='', max_length=255)),
                ('teachType', models.CharField(default='', max_length=255)),
                ('availability', models.CharField(max_length=30)),
                ('archieved', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.institute')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
    ]
