# Generated by Django 3.0.5 on 2021-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolltutors',
            name='availability',
            field=models.CharField(max_length=30),
        ),
    ]
