# Generated by Django 3.0.5 on 2021-03-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210302_0936'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addstudentinst',
            unique_together={('student', 'institute')},
        ),
    ]
