data = {
	'Nursery':['All subjects','English','Maths','Science','evs','hindi'],
	'1':['All subjects','English','Maths','Science','evs','hindi'],
	'2':['All subjects','English','Maths','Science','evs','hindi'],
	'3':['All subjects','English','Maths','Science','evs','hindi'],
	'4':['All subjects','English','Maths','Science','evs','hindi'],
	'5':['All subjects','English','Maths','Science','evs','hindi'],
	'6':['English','Maths','Science','Social Science','hindi','sanskrit','german','french','computer'],
	'7':['English','Maths','Science','Social Science','hindi','sanskrit','german','french','computer'],
	'8':['English','Maths','Science','Social Science','hindi','sanskrit','german','french','computer'],
	'9':['English','maths','science','social science','hindi','sanskrit','german','french','COMPUTER'],
	'10':['English','maths','science','social science','hindi','sanskrit','german','french','COMPUTER'],
	'11':['english','maths','physics','chemistry', 'biology','computer','accounts','business study','economics','geography','history','hindi','sanskrit','art & creativity','physical education','psycology','poltical science','sociology'],
	'12':['english','maths','physics','chemistry', 'biology','computer','accounts','business study','economics','geography','history','hindi','sanskrit','art & creativity','physical education','psycology','poltical science','sociology'],
	'Other':["clat",
"cloud computing",
"communications network",
"complier design",
"company law",
"complexity theory",
"computaltional fluids",
"computer science",
"computer graphics",
"computer networks",
"constitutional law",
"consumer electronics",
"cost accounting",
"costing and financial management",
"criminal law",
"cyber law",
"data compression",
"data interpretation",
"data mining",
"data structures",
"databases",
"design of machine",
"digital communication",
"digital image processing",
"discrete maths",
"economic and commerical maths",
"economics",
"electromagnetic",
"electric circuit design",
"electronics and mircroprocessor",
"embedded networking",
"engine auxilary",
"engineering maths",
"english",
"entrepreneuarship",
"enviornmental science",
"error control coding",
"evidence law",
"family law",
"financial accounting",
"flights dynamics",
"forex management",
"french",
"gate",
"geography",
"german",
"gujrati",
"hindi",
"history",
"ielts",
"ies",
"iit jee",
"image processing",
"income tax",
"information technology law",
"integrated circuits ",
"java",
"korean",
"labour law",
"law",
"law of contracts",
"law of torts",
"linear and diigtal control",
"logic design",
"logical reasoning",
"machine learning",
"maths",
"maths iit jee",
"mechanical eng",
"microprocessors and controllers",
"mobile communication",
"nanoscience",
"nda",
"neet",
"net",
"network analysis",
"network security",
"optical fibre communications",
"operating systems",
"optimization techniques",
"parallel and distributive techniques",
"pattern recognising",
"physics",
"political scince",
"physiology",
"power management",
"programming",
"property law",
"quantitative aptitud",
"quatam computing",
"research methodology",
"reasoning",
"robotics",
"satellite communications",
"signals and system",
"social science",
"soft computing",
"sociology",
"spanish",
"spoken english",
"strategic management",
"tax law",
"taxation law",
"theory of machine",
"thermodynamics",
"UPSC",
"verbal reasoning",
"wave propagtion",
"web design",
"wireless communication",
"wireless sensor network",
"zoology",
]
}
import json
for x in data:
	for y in range(len(data[x])):
		data[x][y] = data[x][y].strip().title()
handle = open('cc.txt','w')
handle.write(json.dumps(data,indent=4,))
handle.close()
