# Generated by Django 3.0.1 on 2020-03-26 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourses',
            fields=[
                ('s_num', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(default='', max_length=5)),
                ('courseName', models.CharField(default='', max_length=100)),
                ('forclass', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AddTutors',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('tutorname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=70, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('courseTaught', models.CharField(default='', max_length=100)),
                ('forclass', models.CharField(default='', max_length=50)),
                ('availability', models.CharField(default='', max_length=50)),
                ('teachType', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveCourses',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('crid', models.CharField(default='', max_length=5)),
                ('crName', models.CharField(default='', max_length=100)),
                ('crclass', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveTutors',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('trname', models.CharField(default='', max_length=100)),
                ('tremail', models.CharField(default='', max_length=100)),
                ('trpassword', models.CharField(default='', max_length=50)),
                ('trphone', models.CharField(default='', max_length=100)),
                ('trcourseTaught', models.CharField(default='', max_length=100)),
                ('trclass', models.CharField(default='', max_length=100)),
                ('travailability', models.CharField(default='', max_length=100)),
                ('trteachType', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignupCoachingCentre',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('instituteCode', models.CharField(default='', max_length=6)),
                ('instituteName', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=70, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(default='', max_length=20)),
                ('confpassword', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('pin', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='SignupStudent',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('studentCode', models.CharField(default='', max_length=6)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=20)),
                ('pin', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)])),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('schoolName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignupTutor',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('tutorCode', models.CharField(default='', max_length=6)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=70, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(default='', max_length=20)),
                ('pin', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)])),
                ('distance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='TeachingType',
            fields=[
                ('s_num', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(default='', max_length=100)),
                ('teachType', models.CharField(default='', max_length=50)),
                ('durationInMonths', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
