# Generated by Django 3.0.1 on 2020-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTeachingType',
            fields=[
                ('s_num', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(default='', max_length=5)),
                ('courseName', models.CharField(default='', max_length=100)),
                ('forclass', models.CharField(default='', max_length=50)),
                ('teachType', models.CharField(default='', max_length=50)),
                ('durationInMonths', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
