# Generated by Django 3.0.1 on 2020-03-28 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_viewteachingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudents',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=70, validators=[django.core.validators.MinLengthValidator(3)])),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('courseName', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
