# Generated by Django 3.0.1 on 2020-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_addstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveStudents',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('stname', models.CharField(default='', max_length=100)),
                ('stemail', models.CharField(default='', max_length=100)),
                ('stphone', models.CharField(default='', max_length=100)),
                ('stcourseName', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
