# Generated by Django 3.0.1 on 2020-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_archivestudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupstudent',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
