# Generated by Django 3.0.1 on 2020-03-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_signupstudent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudents',
            name='feeStatus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='archivestudents',
            name='stfeeStatus',
            field=models.CharField(default='', max_length=100),
        ),
    ]
