# Generated by Django 3.0.1 on 2020-03-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20200329_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFees',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(default='', max_length=100)),
                ('teachType', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(default='', max_length=100)),
                ('feeDuration', models.CharField(default='', max_length=100)),
                ('no_of_installment', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveFees',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('stname', models.CharField(default='', max_length=100)),
                ('stteachType', models.CharField(default='', max_length=100)),
                ('stduration', models.CharField(default='', max_length=100)),
                ('stfeeDuration', models.CharField(default='', max_length=100)),
                ('stno_of_installment', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
