# Generated by Django 3.0.1 on 2020-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_addfees_archivefees'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfees',
            name='feeamt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='archivefees',
            name='stfeeamt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
