# Generated by Django 3.0.1 on 2020-04-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20200329_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingtype',
            old_name='durationInMonths',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='teachingtype',
            name='forclass',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teachingtype',
            name='timePeriod',
            field=models.CharField(default='', max_length=5),
        ),
    ]
