# Generated by Django 3.0.1 on 2020-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20200420_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTutorDetail',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('cid', models.CharField(default='', max_length=5)),
                ('courseName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='addtutors',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='signuptutor',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
