# Generated by Django 3.0.1 on 2020-04-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_auto_20200421_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtutors',
            name='username',
        ),
    ]
