# Generated by Django 3.0.1 on 2020-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_remove_addtutors_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingtype',
            name='duration',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teachingtype',
            name='forclass',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teachingtype',
            name='teachType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teachingtype',
            name='timePeriod',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='viewteachingtype',
            name='durationInMonths',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='viewteachingtype',
            name='forclass',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='viewteachingtype',
            name='teachType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
