# Generated by Django 3.0.1 on 2020-04-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_auto_20200422_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewtutordetail',
            name='courseName',
        ),
        migrations.AddField(
            model_name='addtutors',
            name='instituteName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='viewtutordetail',
            name='instituteName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
