# Generated by Django 3.0.1 on 2020-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_auto_20200423_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTutorInst',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('instituteName', models.CharField(default='', max_length=255)),
                ('instituteCode', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='ViewTutorDetail',
        ),
    ]
