# Generated by Django 3.0.1 on 2020-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_auto_20200424_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCoachingCentre',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
