# Generated by Django 3.0.5 on 2020-05-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_logincoachingcentre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTutorsInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTaught', models.CharField(default='', max_length=100)),
                ('forclass', models.CharField(default='', max_length=255)),
                ('teachType', models.CharField(default='', max_length=255)),
                ('availability', models.DecimalField(decimal_places=0, default=0, help_text='0=>nothing,1=>weekly,2=>weekend,3=>both', max_digits=1)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_cid', related_query_name='tutor_cid', to='tutor.TeachingType')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_username', related_query_name='tutor_username', to='tutor.SignupTutor')),
            ],
        ),
    ]
