# Generated by Django 3.0.5 on 2020-05-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0017_addtutorsinst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtutorsinst',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_cid', related_query_name='tutor_cid', to='tutor.SignupCoachingCentre'),
        ),
    ]
