# Generated by Django 3.0.5 on 2020-05-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_auto_20200507_0512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddTutorInst',
            new_name='enrollTutors',
        ),
        migrations.AlterField(
            model_name='archivetutors',
            name='trname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ArchiveTutors', related_query_name='ArchiveTutors', to='tutor.SignupTutor'),
        ),
    ]
