# Generated by Django 3.0.5 on 2020-05-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_auto_20200518_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolltutors',
            name='username',
        ),
        migrations.AddField(
            model_name='enrolltutors',
            name='signUp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollTutors', to='tutor.SignupTutor'),
        ),
    ]
