# Generated by Django 3.0.5 on 2020-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0022_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudentDetail',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('courseName', models.CharField(default='', max_length=255)),
                ('instituteName', models.CharField(default='', max_length=255)),
                ('teachType', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(default='', max_length=255)),
                ('timePeriod', models.CharField(default='', max_length=255)),
                ('batch', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddStudentInst',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('instituteName', models.CharField(default='', max_length=255)),
                ('instituteCode', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
