# Generated by Django 3.0.5 on 2020-05-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0023_auto_20200527_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudentdetail',
            old_name='duration',
            new_name='forclass',
        ),
        migrations.RemoveField(
            model_name='addstudentdetail',
            name='instituteName',
        ),
        migrations.RemoveField(
            model_name='addstudentdetail',
            name='timePeriod',
        ),
    ]
