# Generated by Django 3.0.5 on 2020-05-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0024_auto_20200527_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddStudentDetail',
        ),
    ]
