# Generated by Django 3.0.5 on 2020-05-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0026_addstudentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feePayed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanceFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='tutor.TeachingType')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='tutor.SignupStudent')),
            ],
        ),
    ]
