# Generated by Django 3.0.5 on 2020-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0027_submitfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentdetail',
            name='feeDisc',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
