# Generated by Django 3.0.5 on 2020-05-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0028_addstudentdetail_feedisc'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfeesc',
            name='final_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addfeesc',
            name='typeOfCharge',
            field=models.DecimalField(decimal_places=0, default=0, help_text='0-> percent || 1-> amount || else-> error', max_digits=1),
            preserve_default=False,
        ),
    ]
