# Generated by Django 3.0.5 on 2020-05-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0029_auto_20200529_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentinst',
            name='conector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AddStudentInst', to='tutor.SignupStudent'),
        ),
    ]
