# Generated by Django 3.0.5 on 2020-05-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0030_addstudentinst_conector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudentdetail',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AddStudentDetail', related_query_name='AddStudentDetail', to='tutor.AddStudentInst'),
        ),
    ]
