# Generated by Django 3.0.5 on 2020-06-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0031_auto_20200531_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitFees',
        ),
    ]
