# Generated by Django 3.0.5 on 2020-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0032_delete_submitfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudentdetail',
            name='instalment',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
    ]
