# Generated by Django 3.0.5 on 2020-06-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0034_instalment_submitfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfees',
            name='feePayed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='submitfees',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
