# Generated by Django 3.0.5 on 2020-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0035_auto_20200604_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitfees',
            name='instalmentPending',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
