# Generated by Django 3.0.5 on 2020-06-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0036_submitfees_instalmentpending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitfees',
            name='instalmentPending',
        ),
    ]
