# Generated by Django 3.0.5 on 2020-06-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0039_auto_20200605_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitfees',
            name='instalmentDue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
