# Generated by Django 3.0.5 on 2020-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0040_submitfees_instalmentdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfees',
            name='instalmentDue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
