# Generated by Django 3.0.5 on 2020-06-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0041_auto_20200605_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitfees',
            name='totalInstallments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
