# Generated by Django 3.0.5 on 2020-06-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0043_submitfees_previousdebt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitfees',
            name='previousDebt',
        ),
    ]
