# Generated by Django 3.0.5 on 2020-06-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0044_remove_submitfees_previousdebt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddStudents',
        ),
    ]
