# Generated by Django 3.0.5 on 2020-06-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0045_delete_addstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveStudents',
        ),
    ]
