# Generated by Django 3.0.5 on 2020-06-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0046_delete_archivestudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveStudents',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('instituteName', models.CharField(default='', max_length=255)),
                ('instituteCode', models.CharField(default='', max_length=255)),
                ('conector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArchiveStudents', to='tutor.SignupStudent')),
            ],
        ),
    ]
