# Generated by Django 3.0.5 on 2020-06-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0048_tutorinstitute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tutorInstitute',
        ),
    ]
