# Generated by Django 3.0.5 on 2020-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0051_auto_20200612_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptutorcontinued',
            name='experience',
            field=models.CharField(default='', max_length=255),
        ),
    ]
