# Generated by Django 3.0.5 on 2020-06-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0052_signuptutorcontinued_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupTutorContinued',
        ),
    ]
