# Generated by Django 3.0.5 on 2020-06-12 11:59

from django.db import migrations, models
import django.db.models.deletion
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0053_delete_signuptutorcontinued'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupTutorContinued',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('availability', models.CharField(default='', max_length=255)),
                ('qualification', models.CharField(default='', max_length=255)),
                ('experience', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=1024)),
                ('gender', models.CharField(default='', help_text='Female/Male', max_length=10)),
                ('courseName', models.CharField(default='', max_length=255)),
                ('forclass', models.CharField(default='', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=tutor.models.userImagePath)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signupTutorContinued', to='tutor.SignupTutor')),
            ],
        ),
    ]
