# Generated by Django 3.0.5 on 2020-06-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0054_signuptutorcontinued'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptutorcontinued',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
