# Generated by Django 3.0.5 on 2020-06-15 04:06

from django.db import migrations, models
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0055_signuptutorcontinued_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAssignment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(default='', max_length=255)),
                ('forclass', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=1024)),
                ('descriptionFile', models.FileField(blank=True, null=True, upload_to=tutor.models.userImagePath)),
                ('requirement', models.DecimalField(decimal_places=0, max_digits=4)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.BooleanField(default=False)),
            ],
        ),
    ]
