# Generated by Django 3.0.5 on 2020-06-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0056_postassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTution',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(default='', max_length=255)),
                ('forclass', models.CharField(default='', max_length=255)),
                ('teachingMode', models.CharField(default='', max_length=255)),
                ('genderPreference', models.CharField(default='', help_text='Female/Male', max_length=10)),
                ('whenToStart', models.DateTimeField()),
                ('description', models.CharField(default='', max_length=1024)),
                ('budget', models.CharField(default='', help_text='Hourly/Monthly', max_length=10)),
                ('numberOfSessions', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('assigned', models.BooleanField(default=False)),
            ],
        ),
    ]
