# Generated by Django 3.0.5 on 2020-06-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0057_posttution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttution',
            name='whenToStart',
            field=models.CharField(default='', max_length=255),
        ),
    ]
