# Generated by Django 3.0.5 on 2020-06-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0058_auto_20200615_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='postassignment',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PostAssignment', to='tutor.SignupStudent'),
        ),
        migrations.AddField(
            model_name='posttution',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PostTution', to='tutor.SignupStudent'),
        ),
    ]
