# Generated by Django 3.0.5 on 2020-06-15 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0059_auto_20200615_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttution',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
