# Generated by Django 3.0.5 on 2020-06-15 06:28

from django.db import migrations, models
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0060_posttution_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postassignment',
            name='descriptionFile',
            field=models.FileField(blank=True, null=True, upload_to=tutor.models.assignmentDescriptionFiles),
        ),
    ]
