# Generated by Django 3.0.5 on 2020-06-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0061_auto_20200615_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtutorsinst',
            name='username',
        ),
    ]
