# Generated by Django 3.0.5 on 2020-06-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0062_remove_addtutorsinst_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtutorsinst',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_username', related_query_name='tutor_username', to='tutor.enrollTutors'),
        ),
    ]
