# Generated by Django 3.0.5 on 2020-06-19 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0064_auto_20200618_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTiming',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(default='', help_text='Comma seperated', max_length=255)),
                ('startTime', models.CharField(default='', max_length=255)),
                ('endTime', models.CharField(default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('coachingCenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BatchTiming', to='tutor.SignupCoachingCentre')),
            ],
        ),
    ]
