# Generated by Django 3.0.5 on 2020-06-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0065_batchtiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtiming',
            name='days',
            field=models.CharField(default='', help_text='Comma seperated', max_length=255),
        ),
        migrations.AlterField(
            model_name='batchtiming',
            name='batchName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
