# Generated by Django 3.0.5 on 2020-06-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0067_batchtiming_original24time'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttution',
            name='budgetVal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
