# Generated by Django 3.0.5 on 2020-06-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0068_posttution_budgetval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupstudent',
            name='pin',
        ),
    ]
