# Generated by Django 3.0.5 on 2020-06-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0069_remove_signupstudent_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuptutor',
            name='pin',
        ),
    ]
