# Generated by Django 3.0.5 on 2020-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0070_remove_signuptutor_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptutorcontinued',
            name='freeDemo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
