# Generated by Django 3.0.5 on 2020-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0071_signuptutorcontinued_freedemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupcoachingcentre',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
