# Generated by Django 3.0.5 on 2020-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0073_remove_signupcoachingcentre_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupcoachingcentre',
            name='confpassword',
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='signuptutor',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
