# Generated by Django 3.0.5 on 2020-06-27 07:49

from django.db import migrations, models
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0074_auto_20200626_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupstudent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=tutor.models.studentImagePath),
        ),
    ]
