# Generated by Django 3.0.5 on 2020-06-28 22:18

from django.db import migrations, models
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0075_signupstudent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupcoachingcentre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=tutor.models.ccImage),
        ),
    ]
