# Generated by Django 3.0.5 on 2020-06-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0076_signupcoachingcentre_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuptutorcontinued',
            name='experience',
        ),
    ]
