# Generated by Django 3.0.5 on 2020-06-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0077_remove_signuptutorcontinued_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptutorcontinued',
            name='experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
