# Generated by Django 3.0.5 on 2020-06-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0078_signuptutorcontinued_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptutorcontinued',
            name='courseName',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signuptutorcontinued',
            name='forclass',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
