# Generated by Django 3.0.5 on 2020-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0079_auto_20200629_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupcoachingcentre',
            name='avatar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='avatar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='signuptutorcontinued',
            name='avatar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
