# Generated by Django 3.0.5 on 2020-07-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0081_auto_20200701_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupcoachingcentre',
            name='latitude',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='signupcoachingcentre',
            name='longitude',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='signupstudent',
            name='latitude',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='signupstudent',
            name='longitude',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='signuptutor',
            name='latitude',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='signuptutor',
            name='longitude',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
