# Generated by Django 3.0.5 on 2020-07-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0083_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeAppointment',
            fields=[
                ('dateTime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('timezone', models.CharField(default='', max_length=35)),
                ('recc', models.BooleanField()),
                ('pattern', models.CharField(default='', max_length=2)),
                ('repeat', models.DecimalField(decimal_places=0, max_digits=3)),
                ('days', models.CharField(default='', max_length=50)),
                ('ending', models.CharField(default='', max_length=10)),
                ('endingDate', models.DateField()),
                ('nomeet', models.DecimalField(decimal_places=0, max_digits=4)),
                ('accepted', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('utcDateTime', models.DateTimeField()),
                ('uid', models.CharField(default='', max_length=50)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MakeAppointment', to='tutor.SignupStudent')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MakeAppointment', to='tutor.SignupTutor')),
            ],
        ),
    ]
