# Generated by Django 3.0.5 on 2020-07-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0084_makeappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeappointment',
            name='utcEndingDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='endingDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='nomeet',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='pattern',
            field=models.CharField(default='', help_text='D-Daily/W=Weekly', max_length=2),
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='recc',
            field=models.BooleanField(help_text='Reccurance'),
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='repeat',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=3),
        ),
    ]
