# Generated by Django 3.0.5 on 2020-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0085_auto_20200706_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeappointment',
            name='nomeet',
        ),
        migrations.AddField(
            model_name='makeappointment',
            name='daysDump',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
