# Generated by Django 3.0.5 on 2020-07-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0086_auto_20200706_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeappointment',
            name='ending',
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='days',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='pattern',
            field=models.CharField(default='', help_text='D-Daily/W=Weekly', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='repeat',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=3, null=True),
        ),
    ]
