# Generated by Django 3.0.5 on 2020-07-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0089_auto_20200711_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveTutors',
        ),
    ]
