# Generated by Django 3.0.5 on 2020-07-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0091_archivetutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivetutors',
            name='instituteCode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archivetutors',
            name='instituteName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='addtutorsinst',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AddTutorsInst', to='tutor.enrollTutors'),
        ),
        migrations.AlterField(
            model_name='enrolltutors',
            name='signUp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollTutors', to='tutor.SignupTutor'),
        ),
    ]
