# Generated by Django 3.0.5 on 2020-07-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0092_auto_20200714_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveTutors',
        ),
    ]
