# Generated by Django 3.0.5 on 2020-07-14 18:23

import django.core.validators
from django.db import migrations, models
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0093_delete_archivetutors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTutors',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('tutorCode', models.CharField(default='', max_length=6)),
                ('username', models.CharField(default='', max_length=100)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=70, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(default='', max_length=20)),
                ('distance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('location', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', help_text='Enter 10 digit phone number', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('latitude', models.CharField(default='0', max_length=20)),
                ('longitude', models.CharField(default='0', max_length=20)),
                ('availability', models.CharField(default='', max_length=255)),
                ('qualification', models.CharField(default='', max_length=255)),
                ('experience', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('description', models.CharField(default='', max_length=1024)),
                ('gender', models.CharField(default='', help_text='Female/Male', max_length=10)),
                ('courseName', models.CharField(default='', max_length=255, null=True)),
                ('forclass', models.CharField(default='', max_length=255, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=tutor.models.userImagePath)),
                ('freeDemo', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('avatar', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('instituteName', models.CharField(default='', max_length=255)),
                ('instituteCode', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
