# Generated by Django 3.0.5 on 2020-07-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0094_archivetutors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddTutors',
        ),
    ]
