# Generated by Django 3.0.5 on 2020-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0095_delete_addtutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivetutors',
            name='teachType',
            field=models.CharField(default='', max_length=255),
        ),
    ]
