# Generated by Django 3.0.5 on 2020-07-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0096_archivetutors_teachtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivestudents',
            name='addStudentDetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ArchiveStudents', to='tutor.AddStudentDetail'),
        ),
    ]
