# Generated by Django 3.0.5 on 2020-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0097_archivestudents_addstudentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudentdetail',
            name='feeDisc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
