# Generated by Django 3.0.5 on 2020-07-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0099_auto_20200717_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveFees',
        ),
    ]
