# Generated by Django 3.0.5 on 2020-07-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0100_delete_archivefees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFees',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(default='', max_length=100)),
                ('forclass', models.CharField(default='', max_length=255)),
                ('teachType', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(default='', max_length=255)),
                ('fee_amt', models.CharField(default='', max_length=100)),
                ('tax', models.CharField(default='', max_length=100)),
                ('final_amt', models.CharField(default='', max_length=100)),
                ('no_of_installment', models.CharField(default='', max_length=100)),
                ('typeOfCharge', models.DecimalField(decimal_places=0, help_text='0-> percent || 1-> amount || else-> error', max_digits=1)),
                ('extra_charge', models.CharField(default='', max_length=255)),
                ('final_amount', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
