# Generated by Django 3.0.5 on 2020-07-23 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0101_archivefees'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfeesc',
            name='discValidity',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='addfeesc',
            name='feeDisc',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
