# Generated by Django 3.0.5 on 2020-07-23 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0102_auto_20200723_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfeesc',
            name='discValidity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
