# Generated by Django 3.0.5 on 2020-07-23 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0104_remove_addfeesc_discvalidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfeesc',
            name='discValidity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
