# Generated by Django 3.0.6 on 2020-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0105_addfeesc_discvalidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupcoachingcentre',
            name='showFees',
            field=models.BooleanField(default=True),
        ),
    ]
