# Generated by Django 3.0.6 on 2020-08-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0106_signupcoachingcentre_showfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourses',
            name='coachingCentre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AddCourses', to='tutor.SignupCoachingCentre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivecourses',
            name='coachingCentre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ArchiveCourses', to='tutor.SignupCoachingCentre'),
            preserve_default=False,
        ),
    ]
