# Generated by Django 3.0.6 on 2020-08-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0107_auto_20200801_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfeesc',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AddFeesC', to='tutor.AddCourses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivefees',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ArchiveFees', to='tutor.AddCourses'),
            preserve_default=False,
        ),
    ]
