# Generated by Django 3.0.6 on 2020-08-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0108_auto_20200810_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfeesc',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AddFeesC', to='tutor.AddCourses'),
        ),
    ]
