# Generated by Django 3.0.6 on 2020-08-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0109_auto_20200811_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingtype',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TeachingType', to='tutor.AddCourses'),
            preserve_default=False,
        ),
    ]
