# Generated by Django 3.0.3 on 2020-08-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0110_teachingtype_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=35)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notice', to='tutor.BatchTiming')),
            ],
        ),
    ]
