# Generated by Django 3.0.5 on 2020-08-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0111_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Fees', models.PositiveIntegerField()),
                ('Duration', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('Validity', models.DateTimeField()),
                ('Discount', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialsinstitute', to='tutor.AddCourses')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialInstitutePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Description', models.TextField()),
                ('Video', models.FileField(upload_to='Tutorials/videos')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='tutor.TutorialInstitute')),
            ],
        ),
    ]
