# Generated by Django 3.0.5 on 2020-08-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0112_tutorialinstitute_tutorialinstituteplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialinstitute',
            name='Archived',
            field=models.BooleanField(default=False),
        ),
    ]
