# Generated by Django 3.0.5 on 2020-08-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0113_tutorialinstitute_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialinstituteplaylist',
            name='Video',
            field=models.FileField(upload_to='playlists'),
        ),
    ]
