# Generated by Django 3.0.5 on 2020-09-02 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0114_auto_20200826_0332'),
    ]

    operations = [

    ]
