# Generated by Django 3.0.5 on 2020-09-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0115_auto_20200903_0327'),
        ('tutor', '0115_tutorialtutors_tutorialtutorsplaylist'),
    ]

    operations = [
    ]
