# Generated by Django 3.0.5 on 2020-09-03 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0116_merge_20200903_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posted_On', models.DateField(auto_now_add=True)),
                ('Review', models.CharField(max_length=2000)),
                ('Rating', models.PositiveIntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorreview', to='tutor.SignupStudent')),
                ('Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tutorreviews', to='tutor.TutorialTutors')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posted_On', models.DateField(auto_now_add=True)),
                ('Review', models.CharField(max_length=2000)),
                ('Rating', models.PositiveIntegerField()),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Institutereviews', to='tutor.TutorialInstitute')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutereview', to='tutor.SignupStudent')),
            ],
        ),
    ]
