# Generated by Django 3.0.5 on 2020-09-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0117_auto_20200903_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewsinstitute',
            options={'ordering': ['-Posted_On']},
        ),
        migrations.AlterModelOptions(
            name='reviewstutor',
            options={'ordering': ['-Posted_On']},
        ),
        migrations.CreateModel(
            name='TutorRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posted_On', models.DateField(auto_now_add=True)),
                ('Review', models.TextField()),
                ('Rating', models.PositiveIntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentenrolledtutor', to='tutor.SignupStudent')),
                ('Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorreviews', to='tutor.SignupTutor')),
            ],
            options={
                'ordering': ['-Posted_On'],
            },
        ),
        migrations.CreateModel(
            name='InstituteRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posted_On', models.DateField(auto_now_add=True)),
                ('Review', models.TextField()),
                ('Rating', models.PositiveIntegerField()),
                ('Institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coachingreviews', to='tutor.SignupCoachingCentre')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentenrolledinstitute', to='tutor.SignupStudent')),
            ],
            options={
                'ordering': ['-Posted_On'],
            },
        ),
    ]
