# Generated by Django 3.1b1 on 2020-09-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0118_auto_20200905_1242'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='OTP',
        #     fields=[
        #         ('otp', models.CharField(max_length=100, primary_key=True, serialize=False)),
        #         ('user', models.CharField(max_length=100)),
        #         ('type', models.CharField(max_length=100)),
        #         ('createdAt', models.DateTimeField(auto_now_add=True)),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='signupcoachingcentre',
        #     name='emailValidated',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='signupstudent',
        #     name='emailValidated',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='signuptutor',
        #     name='emailValidated',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Class', models.CharField(max_length=20)),
                ('Batch', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('exam_duration', models.IntegerField(default=0)),
                ('timezone', models.CharField(max_length=200)),
                ('pass_percentage', models.IntegerField()),
                ('reexam_date', models.DateField(blank=True, null=True)),
                ('calculator', models.BooleanField(default=False)),
                ('imgupload', models.BooleanField(default=False)),
                ('negative_marking', models.BooleanField(blank=True, default=False, null=True)),
                ('negative_marks', models.FloatField(blank=True, null=True)),
                ('tandc', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('resultonmail', models.BooleanField(blank=True, default=False, null=True)),
                ('question_count', models.IntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centername', to='tutor.signupcoachingcentre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tutor.addcourses')),
            ],
        ),
    ]
