# Generated by Django 3.1b1 on 2020-09-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0119_auto_20200911_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('otp', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='signupcoachingcentre',
            name='emailValidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signupstudent',
            name='emailValidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signuptutor',
            name='emailValidated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_ans', models.TextField(max_length=150)),
                ('marks', models.FloatField()),
                ('question_no', models.IntegerField(default=0)),
                ('level', models.CharField(default='medium', max_length=100)),
                ('negative_marks', models.FloatField()),
                ('section', models.CharField(max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneline_question', to='tutor.exam')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_ans', models.CharField(max_length=1000)),
                ('marks', models.FloatField()),
                ('question_no', models.IntegerField(default=0)),
                ('level', models.CharField(default='medium', max_length=100)),
                ('negative_marks', models.FloatField(default=0)),
                ('section', models.CharField(default='A', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_question', to='tutor.exam')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=150)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tutor.multiplequestion')),
            ],
        ),
        migrations.CreateModel(
            name='LongAnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('level', models.CharField(default='medium', max_length=100)),
                ('correct_ans', models.TextField(max_length=350)),
                ('marks', models.FloatField()),
                ('question_no', models.IntegerField(default=0)),
                ('negative_marks', models.FloatField()),
                ('section', models.CharField(max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjective_question', to='tutor.exam')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(blank=True, max_length=10, null=True)),
                ('option2', models.CharField(blank=True, max_length=10, null=True)),
                ('correct_ans', models.CharField(max_length=10)),
                ('marks', models.FloatField()),
                ('question_no', models.IntegerField(default=0)),
                ('level', models.CharField(default='medium', max_length=100)),
                ('negative_marks', models.FloatField()),
                ('section', models.CharField(max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolean_question', to='tutor.exam')),
            ],
        ),
    ]
