# Generated by Django 3.1b1 on 2020-09-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0122_auto_20200917_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='BatchTimingTutor',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(default='', max_length=255)),
                ('days', models.CharField(default='', help_text='Comma seperated', max_length=255)),
                ('startTime', models.CharField(default='', max_length=255)),
                ('endTime', models.CharField(default='', max_length=255)),
                ('original24time', models.CharField(default='', help_text='Comma seperated', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BatchTutor', to='tutor.signuptutor')),
            ],
        ),
    ]
