# Generated by Django 3.1.3 on 2021-07-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFeesC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='', max_length=100, null=True)),
                ('forclass', models.CharField(default='', max_length=255, null=True)),
                ('teachType', models.CharField(default='', max_length=255, null=True)),
                ('duration', models.CharField(default='', max_length=255, null=True)),
                ('fee_amt', models.CharField(default='', max_length=100, null=True)),
                ('tax', models.CharField(default='', max_length=100, null=True)),
                ('final_amt', models.CharField(default='', max_length=100, null=True)),
                ('no_of_installment', models.CharField(default='', max_length=100, null=True)),
                ('typeOfCharge', models.DecimalField(decimal_places=0, help_text='0-> percent || 1-> amount || else-> error', max_digits=1)),
                ('extra_charge', models.CharField(default='', max_length=255)),
                ('feeDisc', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('discValidity', models.DateTimeField(blank=True, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feesstatus', models.CharField(default='Un paid', max_length=10, null=True)),
                ('archieved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AddFeesC', to='courses.courses')),
                ('intitute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.institute')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalFee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('feePayed', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('instalmentDue', models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True)),
                ('totalInstallments', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('feesstatus', models.CharField(default='Un paid', max_length=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('fees', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_fees', to='fees.addfeesc')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalmentNum', models.DecimalField(decimal_places=0, max_digits=3)),
                ('paymentExp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentDone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('feeObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Instalment', to='fees.submitfees')),
            ],
        ),
    ]
