# Generated by Django 3.1.7 on 2021-03-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=60)),
                ('room', models.CharField(max_length=30)),
                ('fl', models.CharField(max_length=2)),
                ('ts', models.CharField(max_length=30)),
            ],
        ),
    ]
