# Generated by Django 3.0.5 on 2021-03-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatapplication',
            name='fl',
            field=models.IntegerField(max_length=2),
        ),
    ]
