# Generated by Django 3.0.5 on 2021-03-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210316_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatapplication',
            name='names',
            field=models.CharField(default='Welcome', max_length=60),
        ),
    ]
