# Generated by Django 3.0.5 on 2021-03-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210316_1643'),
        ('chat', '0003_auto_20210317_0109'),
    ]

    operations = [
    ]
