# Generated by Django 3.0.5 on 2021-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_merge_20210317_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatapplication',
            name='chatroom',
            field=models.CharField(default='Welcome', max_length=30),
        ),
    ]
