# Generated by Django 3.0.5 on 2021-03-25 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatapplication_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatapplication',
            name='dtime',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='chatapplication',
            name='fl',
            field=models.IntegerField(),
        ),
    ]
