# Generated by Django 3.0.5 on 2021-03-25 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210325_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatapplication',
            name='dtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
