# Generated by Django 3.1.3 on 2021-07-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayname', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=80)),
                ('txndate', models.CharField(max_length=80)),
                ('feeCategory', models.CharField(max_length=255)),
                ('txnamount', models.CharField(max_length=50)),
                ('txnexpdate', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('otp', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayname', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=80)),
                ('txndate', models.CharField(max_length=80)),
                ('feeCategory', models.CharField(max_length=255)),
                ('txnamount', models.CharField(max_length=50)),
                ('txnexpdate', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='tutorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeCategory', models.CharField(choices=[('Select', 'Select'), ('Premium', 'Premium'), ('Diamond', 'Diamond')], default='Select', max_length=20)),
                ('fee_amt', models.IntegerField(default=0)),
                ('feeCycle', models.CharField(default='', max_length=255, null=True)),
                ('feeDisc', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('discValidity', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.CharField(max_length=8)),
                ('coupValidity', models.DateTimeField(blank=True, null=True)),
                ('feesstatus', models.CharField(default='Deactive', max_length=10, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorpayment', to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='institutePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeCategory', models.CharField(choices=[('Select', 'Select'), ('Premium', 'Premium'), ('Diamond', 'Diamond')], default='Select', max_length=20)),
                ('fee_amt', models.IntegerField(default=0)),
                ('feeCycle', models.CharField(default='', max_length=255, null=True)),
                ('feeDisc', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('discValidity', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.CharField(max_length=8)),
                ('coupValidity', models.DateTimeField(blank=True, null=True)),
                ('feesstatus', models.CharField(default='Deactive', max_length=10, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutepayment', to='accounts.institute')),
            ],
        ),
    ]
