# Generated by Django 3.0.5 on 2021-03-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='photo',
            field=models.ImageField(blank=True, default='default-man.png', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='default-man.png', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='default-man.png', null=True, upload_to='users/'),
        ),
    ]
