# Generated by Django 3.0.5 on 2021-02-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorexam',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='tutorexam',
            name='course',
        ),
        migrations.AddField(
            model_name='tutorexam',
            name='courseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorexam',
            name='forclass',
            field=models.CharField(default='', max_length=255),
        ),
    ]
