# Generated by Django 3.0.5 on 2021-03-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_tutorstudentanswer_tutorstudentexamresult_tutorstudentmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamresult',
            name='annotated_copies',
            field=models.FileField(blank=True, null=True, upload_to='annotated_pdf'),
        ),
        migrations.AddField(
            model_name='tutorstudentexamresult',
            name='annotated_copies',
            field=models.FileField(blank=True, null=True, upload_to='annotated_pdf'),
        ),
    ]
