# Generated by Django 3.0.5 on 2021-02-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.FileField(upload_to='notes/Institute')),
                ('title', models.CharField(max_length=2000)),
                ('subject', models.CharField(max_length=3000)),
                ('description', models.TextField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutornotes', to='accounts.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='NotesInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.FileField(upload_to='notes/Institute')),
                ('title', models.CharField(max_length=2000)),
                ('subject', models.CharField(max_length=3000)),
                ('description', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centernotes', to='accounts.Institute')),
            ],
        ),
    ]
