# Generated by Django 3.0.5 on 2021-03-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notesinstitute_forclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesinstitute',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notestutor',
            name='forclass',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='notestutor',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notesinstitute',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='notestutor',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
