from django.contrib import admin
from .models import *

admin.site.register(BatchTiming)
admin.site.register(PostAssignment)
admin.site.register(PostTution)
admin.site.register(LoginCoachingCentre)
admin.site.register(SignupTutorContinued)
admin.site.register(SubmitFees)
admin.site.register(Instalment)
admin.site.register(AddFeesC)
admin.site.register(AddStudentDetail)
admin.site.register(AddStudentInst)
admin.site.register(enrollTutors)
admin.site.register(AddTutorsInst)
admin.site.register(SignupCoachingCentre)
admin.site.register(AddCourses)
admin.site.register(ArchiveCourses)
admin.site.register(TeachingType)
admin.site.register(ViewTeachingType)
admin.site.register(SignupTutor)
admin.site.register(ArchiveTutors)
admin.site.register(SignupStudent)
admin.site.register(ArchiveStudents)
admin.site.register(AddFees)
admin.site.register(ArchiveFees)
admin.site.register(School)
admin.site.register(TutorialInstitute)
admin.site.register(TutorialTutors)
admin.site.register(ReviewsInstitute)
admin.site.register(ReviewsTutor)
admin.site.register(MakeAppointment)
