# Generated by Django 3.0.5 on 2021-03-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingtype',
            name='archieved',
            field=models.BooleanField(default=False),
        ),
    ]
