from django.urls import path
from .views import *
from .api import *

urlpatterns = [
    path('Add', AddExam, name="addexam"),
    path('view/all', ListExams, name='viewexams'),
    path('delete/<exam_id>', deleteExam, name='DeleteExam'),
    path('edit/<exam_id>', Editexam, name='EditExam'),
    path('toggle/<exam_id>', ToggleExam, name='toggle'),
    path('classes', FindCourses, name="findCourse"), #altered
    path('teachings', FindTeaching, name="findTeaching"), #altered
    path('Questions/all/add', QuestionsSection, name="questionsection"),
    path('Questions/add/<exam_id>', CreateQuestions, name='questions'),
    path('Questions/edit/all', EditExamQuestions, name="editexamquestions"),
    path('Questions/edit/<exam_id>', EditQuestions, name="editquestions"),
    path('Questions/shortquestions/edit/<question_id>',
         EditShortQuestions, name='shortansedit'),
    path('Questions/shortquestions/delete/<question_id>',
         DeleteShortQuestions, name='shortansdelete'),
    path('Questions/longquestions/edit/<question_id>',
         EditLongQuestions, name='longansedit'),
    path('Questions/longquestions/delete/<question_id>',
         DeleteLongQuestions, name='longansdelete'),
    path('Questions/booleanquestions/edit/<question_id>',
         EditBooleanQuestions, name='booleanansedit'),
    path('Questions/multiplequestions/edit/<question_id>',
         EditMultipleQuestions, name='multipleansedit'),
    path('Questions/booleanquestions/delete/<question_id>',
         DeleteBooleanQuestions, name='booleanansdelete'),
    path('Questions/multiplequestions/delete/<question_id>',
         DeleteMultipleQuestions, name='multipleansdelete'),
    path('Student/Exams/All', StudentExamsAll, name="studentexams"),
    path('Student/Calculator', calculator, name="calc"),
    path('Student/Exam/<pk>', instruction, name="instruction"),
    path('Student/Exam/start/<pk>', start_exam, name="start_exam"),
    path('Student/all/Questions/<pk>', view_questions, name="view_questions"),
    path('student/Exam/Submitted', submitted, name="submitted"),
    path('Student/Exam/Store/Data', store_data, name="store_data"),
    #Saving Ans
    path('multiple_ans/',multiple_ans, name='multiple_ans'),
    path('short_ans/',short_ans, name='short_ans'),
    path('long_ans/',long_ans, name='long_ans'),
    path('tof_ans/',tof_ans, name='tof_ans'),
    # Tutor Exam
    path('Tutor/Exam/Add/All', ExamTutor, name="examtutor"),
    path('Tutor/Exams/View/all', ViewExamTutor, name="viewexamstutor"),
    path('Tutor/tutortoggle/<exam_id>', ToggleTutorExam, name='tutortoggle'),
    path('Tutor/delete/<exam_id>', DeleteTutorExam, name='DeleteTutorExam'),
    path('Tutor/Exam/Edit/<exam_id>', EditExamTutor, name="edittutorexams"),
    path('Tutor/add/Question/Exam/all',
         addQuestionsTutor, name="addquestionstutor"),
    path('Tutor/Question/<exam_id>', CreateQuestionsTutor,
         name="createquestionstutor"),
    path('Tutor/Questions/Edit/all',
         EditExamQuestionsTutor, name="questionalltutor"),
    path('Tutor/Question/edit/<exam_id>',
         EditQuestionsTutor, name="editquestionstutor"),
    path('Tutor/Exam/Questions/shortquestions/edit/<question_id>',
         EditShortQuestionsTutor, name='shortansedittutor'),
    path('Tutor/Exam/Questions/longquestions/edit/<question_id>',
         EditLongQuestionsTutor, name='longansedittutor'),
    path('Tutor/Exam/Questions/booleanquestions/edit/<question_id>',
         EditBooleanQuestionsTutor, name='booleanansedittutor'),
    path('Tutor/Exam/Questions/multiplequestions/edit/<question_id>',
         EditMultipleQuestionsTutor, name='multipleansedittutor'),

    # API-URLs

    path('TutorExam-api',
         TutorExamAPI, name='tutor-exam-api'),
    path('Tutor/Exam/multiple-answer-api',
         TutorMultipleAnswerAPI, name='tutor-multiple-answer-api'),
    path('Tutor/Exam/Questions/longquestions-api',
         TutorLongAnswerQuestionAPI, name='tutor-long-answer-question-api'),
    path('Tutor/Exam/Questions/tutor-short-answer-questions-api',
         TutorShortAnswerQuestionAPI, name='tutor-short-answer-question-api'),
    path('Tutor/Exam/Questions/tutor-boolean-answer-questions-api',
         TutorBooleanQuestionAPI, name='tutor-boolean-answer-question-api'),
    path('Tutor/Exam/Questions/tutor-multiple-questions-api',
         TutorMultipleQuestionAPI, name='tutor-multiple-question-api'),
    path('Exam-api',
         ExamAPI, name='exam-api'),
    path('Exam/multiple-answer-api',
         MultipleAnswerAPI, name='multiple-answer-api'),
    path('Exam/Questions/long-questions-api',
         LongAnswerQuestionAPI, name='long-answer-question-api'),
    path('Exam/Questions/short-answer-questions-api',
         ShortAnswerQuestionAPI, name='short-answer-question-api'),
    path('Exam/Questions/boolean-answer-questions-api',
         BooleanQuestionAPI, name='boolean-answer-question-api'),
    path('Exam/Questions/multiple-questions-api',
         MultipleQuestionAPI, name='multiple-question-api'),
]
