# Generated by Django 3.0.5 on 2021-03-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0003_auto_20210320_2029'),
        ('tutorials', '0003_auto_20210309_0951'),
        ('accounts', '0002_auto_20210302_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTutorNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, null=True)),
                ('buy_at', models.DateField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.NotesTutor')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Student')),
            ],
            options={
                'unique_together': {('note', 'student')},
            },
        ),
        migrations.CreateModel(
            name='BuyTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, null=True)),
                ('buy_at', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Student')),
                ('tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorials.TutorialInstitute')),
            ],
            options={
                'unique_together': {('tutorial', 'student')},
            },
        ),
        migrations.CreateModel(
            name='BuyInstituteNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, null=True)),
                ('buy_at', models.DateField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.NotesInstitute')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Student')),
            ],
            options={
                'unique_together': {('note', 'student')},
            },
        ),
    ]
