# Generated by Django 3.0.5 on 2021-03-26 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210320_2029'),
        ('accounts', '0002_auto_20210302_0936'),
        ('exams', '0003_tutorstudentanswer_tutorstudentexamresult_tutorstudentmapping'),
        ('tutorials', '0003_auto_20210309_0951'),
        ('buy_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInstituteTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, null=True)),
                ('buy_at', models.DateField(auto_now_add=True)),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.TutorialInstitute')),
            ],
            options={
                'unique_together': {('tutorial', 'student')},
            },
        ),
        migrations.CreateModel(
            name='BuyTutorExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, null=True)),
                ('buy_at', models.DateField(auto_now_add=True)),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.TutorExam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='BuyTutorTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0, null=True)),
                ('buy_at', models.DateField(auto_now_add=True)),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.TutorialTutors')),
            ],
            options={
                'unique_together': {('tutorial', 'student')},
            },
        ),
        migrations.AlterField(
            model_name='buyinstitutenotes',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.NotesInstitute'),
        ),
        migrations.AlterField(
            model_name='buyinstitutenotes',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='buyinstitutenotes',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='buytutornotes',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.NotesTutor'),
        ),
        migrations.AlterField(
            model_name='buytutornotes',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='buytutornotes',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
        migrations.DeleteModel(
            name='BuyTutorial',
        ),
    ]
