# Generated by Django 3.0.5 on 2021-03-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_items', '0004_auto_20210327_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='order_id',
        ),
    ]
