# Generated by Django 3.0.5 on 2021-03-27 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_items', '0005_remove_revenue_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
