# Generated by Django 3.0.5 on 2021-03-27 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buy_items', '0006_auto_20210327_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
