# Generated by Django 3.1.3 on 2021-06-20 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('forclass', models.CharField(default='', max_length=150)),
                ('Fees', models.PositiveIntegerField()),
                ('Duration', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('Validity', models.DateTimeField(blank=True, null=True)),
                ('Discount', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('Archived', models.BooleanField(default=False)),
                ('freeEnrolled', models.BooleanField(default=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialsinstitute', to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialTutors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Course', models.CharField(default='', max_length=150)),
                ('forclass', models.CharField(default='', max_length=150)),
                ('Fees', models.PositiveIntegerField()),
                ('Duration', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('Validity', models.DateTimeField(blank=True, null=True)),
                ('Discount', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('Archived', models.BooleanField(default=False)),
                ('Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialstutor', to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialTutorsPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Description', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Video', models.FileField(upload_to='playlists')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorplaylist', to='tutorials.tutorialtutors')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialInstitutePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Description', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Video', models.FileField(upload_to='playlists')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='tutorials.tutorialinstitute')),
            ],
        ),
    ]
