# Generated by Django 3.0.5 on 2021-02-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Fees', models.PositiveIntegerField()),
                ('Duration', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('Validity', models.DateTimeField()),
                ('Discount', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('Archived', models.BooleanField(default=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialsinstitute', to='courses.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialTutors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Fees', models.PositiveIntegerField()),
                ('Duration', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('Validity', models.DateTimeField()),
                ('Discount', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('Archived', models.BooleanField(default=False)),
                ('Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialstutor', to='accounts.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialTutorsPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Description', models.TextField()),
                ('Video', models.FileField(upload_to='playlists')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorplaylist', to='tutorials.TutorialTutors')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialInstitutePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Description', models.TextField()),
                ('Video', models.FileField(upload_to='playlists')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='tutorials.TutorialInstitute')),
            ],
        ),
    ]
