# Generated by Django 3.0.5 on 2021-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialinstitute',
            name='forclass',
            field=models.CharField(default='', max_length=150),
        ),
    ]
