# Generated by Django 3.0.5 on 2021-03-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorialinstitute_forclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialinstitute',
            name='Validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialtutors',
            name='Validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
